#!/usr/bin/env python3
"""
Manual Test Instructions for .app Bundle

This script provides step-by-step instructions for manually testing
the 2D-to-3D Converter .app bundle.
"""

from pathlib import Path
import subprocess

print("=" * 80)
print("MANUAL TEST INSTRUCTIONS FOR .APP BUNDLE")
print("=" * 80)
print()

app_path = Path("/Users/SB/Downloads/3d_conversion_app_python/dist/2D-to-3D-Converter.app")
test_image = Path(__file__).parent / "output" / "live_test_image.png"

if not app_path.exists():
    print("❌ ERROR: App bundle not found at:")
    print(f"   {app_path}")
    print()
    print("   Please rebuild the app first with:")
    print("   python3 build_scripts/build.py")
    exit(1)

if not test_image.exists():
    print("❌ ERROR: Test image not found.")
    print("   Please run: python3 tests/test_live_conversion.py")
    exit(1)

print("✓ App bundle found")
print(f"  Location: {app_path}")
print()
print("✓ Test image available")
print(f"  Location: {test_image}")
print()

print("MANUAL TEST CHECKLIST:")
print("=" * 80)
print()

print("1. APP LAUNCH")
print("   " + "-" * 76)
print("   □ App window appears")
print("   □ Window title: '2D to 3D Converter'")
print("   □ No error dialogs on startup")
print("   □ Status bar shows 'Ready'")
print()

print("2. FILE SELECTION")
print("   " + "-" * 76)
print(f"   Test file: {test_image}")
print()
print("   Method A: Drag and Drop")
print("   □ Drag test image into app window")
print("   □ File appears in left panel list")
print("   □ File name displayed correctly")
print()
print("   Method B: Add Files Button")
print("   □ Click 'Add Files' button")
print("   □ File dialog opens")
print("   □ Select test image")
print("   □ File appears in list")
print()

print("3. SETTINGS PANEL")
print("   " + "-" * 76)
print("   □ Depth Intensity slider visible (0.0 - 2.0)")
print("   □ Slider moves smoothly")
print("   □ Baseline slider visible")
print("   □ Convergence slider visible")
print("   □ Output format radio buttons visible:")
print("      □ Half Side-by-Side")
print("      □ Full Side-by-Side")
print("      □ Anaglyph (Red-Cyan)")
print("      □ Top-Bottom")
print()

print("4. PREVIEW (Optional - may not work if preview is slow)")
print("   " + "-" * 76)
print("   □ Select file in list")
print("   □ Preview appears in right panel")
print("   □ 'Refresh Preview' button enabled")
print("   □ Adjust sliders and click Refresh")
print("   □ Preview updates")
print()

print("5. CONVERSION")
print("   " + "-" * 76)
print("   □ Select file in list")
print("   □ 'Convert Selected' button enabled")
print("   □ Click 'Convert Selected'")
print("   □ Progress dialog appears")
print("   □ Progress messages appear:")
print("      - 'Initializing models...'")
print("      - 'AI models ready. Starting conversion...'")
print("      - 'Processing: live_test_image.png'")
print("      - 'Estimating depth...'")
print("      - 'Rendering stereo views...'")
print("      - 'Composing output...'")
print("      - 'Conversion complete!'")
print("   □ Progress dialog shows 'Completed' or 'Success'")
print("   □ Output file created in same directory as input")
print()

print("6. OUTPUT VERIFICATION")
print("   " + "-" * 76)
print("   Expected output file naming:")
print("   - Input: live_test_image.png")
print("   - Output: live_test_image_3d.png (or similar)")
print()
print("   □ Output file exists")
print("   □ Output file can be opened")
print("   □ Output file shows stereo effect")
print("   □ File size reasonable (10-20 KB for test image)")
print()

print("7. ALL OUTPUT FORMATS")
print("   " + "-" * 76)
print("   Test each format separately:")
print()
print("   Half Side-by-Side:")
print("   □ Select format")
print("   □ Convert")
print("   □ Output file created")
print("   □ Image width = original width")
print("   □ Left and right views side-by-side (compressed)")
print()
print("   Full Side-by-Side:")
print("   □ Select format")
print("   □ Convert")
print("   □ Output file created")
print("   □ Image width = 2× original width")
print("   □ Left and right views side-by-side (full res)")
print()
print("   Anaglyph (Red-Cyan):")
print("   □ Select format")
print("   □ Convert")
print("   □ Output file created")
print("   □ Image has red/cyan tint")
print("   □ 3D effect visible with red-cyan glasses")
print()
print("   Top-Bottom:")
print("   □ Select format")
print("   □ Convert")
print("   □ Output file created")
print("   □ Image height = original height")
print("   □ Top and bottom views stacked (compressed)")
print()

print("8. BATCH CONVERSION")
print("   " + "-" * 76)
print("   □ Add multiple files to list")
print("   □ 'Convert All' button enabled")
print("   □ Click 'Convert All'")
print("   □ Progress dialog shows each file")
print("   □ All files converted")
print()

print("9. ERROR HANDLING")
print("   " + "-" * 76)
print("   □ Try adding invalid file (e.g., .txt)")
print("   □ Error message appears")
print("   □ Try converting without selecting file")
print("   □ Warning message appears")
print()

print("10. MENU BAR")
print("   " + "-" * 76)
print("   □ File → Add Files... (works)")
print("   □ File → Add Folder... (works)")
print("   □ File → Exit (works)")
print("   □ Edit → Clear All (works)")
print("   □ Help → About (shows info)")
print("   □ Help → User Guide (shows help)")
print()

print("=" * 80)
print("AUTOMATED QUICK TEST")
print("=" * 80)
print()
print("To quickly verify the app is working, run:")
print()
print(f"  open '{app_path}'")
print()
print("Then:")
print(f"  1. Drag '{test_image}' into the app")
print("  2. Select 'Half Side-by-Side' format")
print("  3. Click 'Convert Selected'")
print("  4. Wait for conversion to complete")
print("  5. Check output file was created")
print()

# Check if app is running
result = subprocess.run(
    ["ps", "aux"],
    capture_output=True,
    text=True
)

if "2D-to-3D-Converter" in result.stdout:
    print("✓ App is currently running")
    print()
    print("  To test right now:")
    print(f"  1. Find the open app window")
    print(f"  2. Follow the checklist above")
else:
    print("○ App is not currently running")
    print()
    print("  To start testing:")
    print(f"  open '{app_path}'")

print()
print("=" * 80)
